name: GitHub Metrics Embed

on:
  schedule:
    - cron: "0 2 * * *"     # Executa todo dia às 02:00 (horário de Brasília)
  workflow_dispatch:        # Permite rodar manualmente

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Lowingx
          template: classic
          base: header, activity, community, repositories, metadata, languages
          config_timezone: America/Sao_Paulo
          config_skip_empty: true
          config_order: header, activity, community, repositories, languages, metadata
          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year
          plugin_languages: true
          plugin_languages_limit: 8
          plugin_languages_details: percentage, bytes-size
          plugin_activity: true
          plugin_activity_limit: 12
          plugin_activity_days: 90
          plugin_activity_visibility: public
          filename: github-metrics.svg
          output: svg
EOF
